### ISSUE TITLE
Accompanying score files

### ISSUE THREAD

**Issue by napulen** [MarkGotham/When-in-Rome#13]
## Food for thought related to files that have no accompanying score:

Several collections have missing accompanying scores in this repository, **but** have scores elsewhere (with a specified or unspecified license). More specifically:

- Scores from the TAVERN dataset
- Bach Chorales
- Beethoven Piano Sonatas
- Beethoven String Quartets
- Haydn String Quartets
- Some on the `Variations and Grounds`

How about a standardized "link" file accompanying each analysis file in this repository, which leads to wherever those scores can be found/requested.

For example, for the file `/Corpus/Variations_and_Grounds/Mozart,_Wolfgang_Amadeus/_/K025`, which currently has an `analysis_A.txt` (and `analysis_B.txt`) file but no `score.mxl`, something like this would be included within the folder:

`link_to_score.txt`
```
Score: https://github.com/jcdevaney/TAVERN/blob/master/Mozart/K025/Krn/K025.krn
Format: Humdrum
Attribution: Devaney et al.
```

Plus any other fields that are adequate for that file (e.g., `License:` or `Citation:`)

I have verified that TAVERN, Bach Chorales, Beethoven String Quartets, Haydn String Quartets all have digital scores that we can link to, regardless of whether there is permission to redistribute them or not. This practice seems to be used by other meta-corpus projects, such as `muspy` and `mirdata`.

Leaving GitHub issues on the original repositories is of course another option, it's possible that the researchers are willing to share these scores freely and they may have just omitted to include a permissive license.

**Comment by MarkGotham** [comment]
Thanks @napulen! I've been wondering about implementing something like that and would greatly welcome help with thinking it all through and putting it into practice. Here are some thoughts, likewise shared publicly in case anyone else wants to chip in.

Among other benefits, it would be good to avoid holding duplicate files in multiple locations.
- On the up side, we'd be able to keep up with any remote changes and also avoid uncertainly over whether the files are (still) identical. We're working on a dedicated repo for the lieder scores, for instance, so that would also be a candidate for change. That could also help make the repo more consistent as the lieder present the only cases where there are scores without analyses. 
- The drawback, of course, is that external URLs may change, breaking our links.

If we go with it, this could potentially extend to certain analyses, specifically anything unmodified (so currently all and only those Bach and Monteverdi analyses to have come from the music21 corpus). I know that there are more `rntxt` analyses soon to be released so we could also point to them rather than copying.

If we extend to analyses, then we'd either need `link_to_analysis` in addition to `link_to_score` files, or else go the other way and simply have `about` files in every folder for all of this information (with blank entries as necessary).

The files that are more unique to this repo such as `feedback` would remain.

Apart from the question of duplication, I think there are plans in music21 to develop the provision for working with such 'virtual corpora' (i.e. the kind of list of URLs to scores that'd we'd be providing here) so there may be potential for coordinated progress.

Finally, re licensing, I am not a lawyer so I can't speak authoritatively on this, but the intention in this repo (as stated in the read me) is to provide new material including new conversions of existing analyses to make everything more readily interoperable. In that case, we leave the licensing for original content with its originator and set the license here specifically the conversion and edit in those cases. The source is also set out very clearly in each file.

**Comment by MarkGotham** [comment]
p.s. I've freshened up the [contents script](https://github.com/MarkGotham/When-in-Rome/commit/0ebdf7669eed731ef87dcad3fc8d178fd15e1962) to help keep track of this.

**Comment by MarkGotham** [comment]
Decision:
- scores available in formats that music21 can parse: leave.
- scores only available in other formats (notably musescore): provide local mxl conversion.
