### ISSUE TITLE
Feedback on analysis needs update

### ISSUE THREAD

**Issue by giamic** [MarkGotham/When-in-Rome#61]
It seems like the feedback on the analyses has changed quite a lot with respect to the version stored in the github repo. I would check these differences and update the version on the repo. Or, we could remove all feedbacks altogether and provide the users with a super simple way to reobtain them.

**Comment by MarkGotham** [comment]
Hey @giamic.

Thanks for this.

There should no longer be feedback on the analyses stored on the GitHub repo -- where are you finding those files?

This is partly because the exact type of feedback has changed (as you notice) and will change further as we develop, and also partly because of repo bloat (look at the example folder!).

**Comment by giamic** [comment]
My bad. Apparently I had somehow downloaded an older version of the repo which still had some feedbacks. All gone now.
