### ISSUE TITLE
Broken Humdrum score links

### ISSUE THREAD

**Issue by malcolmsailor** [MarkGotham/When-in-Rome#92]
Some of the links for remote Humdrum scores seem to be broken. For example `Corpus/Keyboard_Other/Bach,_Johann_Sebastian/The_Well-Tempered_Clavier_I/22_fugue/remote.json` has `https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/bach/keyboard/wtc-1&file=wtc1f22.krn&f=kern` but this url seems to return an empty page (tried opening it both with the Python `requests` library, wget, and my browser).

**Comment by malcolmsailor** [comment]
This link (found by browsing `kern.humdrum.org`) seems to work: `https://kern.humdrum.org/cgi-bin/ksdata?l=osu/classical/bach/wtc-1&file=wtc1f22.krn&f=kern`

We may want to ask Craig Sapp what's going on with these URLs.

**Comment by malcolmsailor** [comment]
Another related issue is that some `remote_score` don't seem to be URLs. For example, in `Corpus/Quartets/Haydn,_Franz_Joseph/Op74_No3/2/remote.json` we have `"remote_score_krn": "napulen/humdrum-haydn-quartets/master/kern/op74n3-02.krn"`. I guess this is meant to be Github URL?

**Comment by malcolmsailor** [comment]
I just wrote the following script to find all the broken links and/or empty score links in the corpus:
```python
import json
import os
from functools import partial
from multiprocessing import Manager
from multiprocessing.pool import Pool

import requests
import sh

fd_result = sh.fd(  # type:ignore
    "--color", "never", "remote.*json", os.environ["WHEN_IN_ROME_DIR"]
)
files = fd_result.stdout.decode().strip().split("\n")


def download_file(url, empty_files, errors, invalid_urls):
    print(f"Downloading {url}")
    try:
        response = requests.get(url)
    except requests.exceptions.MissingSchema:
        invalid_urls.append(url)
        return

    # Check if the request was successful (status code 200)
    if response.status_code == 200:
        # Open a file for writing in binary mode
        if not response.content:
            empty_files.append(url)
    else:
        errors.append(url)


def main():
    manager = Manager()
    empty_files = manager.list()
    errors = manager.list()
    invalid_urls = manager.list()
    files_to_download = []
    download_f = partial(
        download_file, empty_files=empty_files, errors=errors, invalid_urls=invalid_urls
    )
    for f in files:
        with open(f) as inf:
            data = json.load(inf)
        for key in [
            "remote_score_mscx",
            "remote_score_krn",
            "remote_score_mxl",
        ]:
            if key in data:
                url = data[key]
                if not isinstance(url, str):
                    invalid_urls.append(f)
                    continue
                files_to_download.append(url)

    with Pool(24) as pool:
        list(pool.imap(download_f, files_to_download))
    print(f"{len(empty_files)} empty files")
    for f in empty_files:
        print(f)

    print(f"{len(errors)} errors")
    for f in errors:
        print(f)

    print(f"{len(invalid_urls)} invalid URLS")
    for f in invalid_urls:
        print(f)


if __name__ == "__main__":
    main()
```

From this, it seems that
- all the Bach fugues and Corelli pieces (on `kern.humdrum.org`) return empty pages.
- 536 scores, all beginning with `https://raw.githubusercontent.com` give a status code other than 200 when downloading (by inspection, at least some of these are 404).
- the Haydn quartets have invalid URLs

**Comment by malcolmsailor** [comment]
> 536 scores, all beginning with https://raw.githubusercontent.com give a status code other than 200 when downloading (by inspection, at least some of these are 404).

On closer inspection these seem to be from 3 sources:

1. ABC
2. Mozart Piano Sonatas
3. Gotham ChoraleCorpus

I believe the URLs are out of date.

**Comment by MarkGotham** [comment]
Great thanks for this investigative work!

I'd suggest:
- keeping this issue open and restricted to Kern scores.
- fixing the others or starting new issues as needed (clear cases like the Haydn 4tets and DCML scores now done and deleted from the above)
- adding a version of your checking code [here](https://github.com/MarkGotham/When-in-Rome/tree/master/Code/test_remote_urls.py) and creating a new issue reminding me/us to split this into two: `get_remote_scores` user function and `test_remote_score_URLs` testing validity

So sticking with the krn score URLs ...

Bach notes:
- `https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/bach/keyboard/wtc-1&file=wtc1f22.krn&f=kern` is blank
- `https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/bach/keyboard/wtc1&file=wtc1f22.krn&f=kern` is access unsuccessful
- `https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/bach/keyboard/wtc&file=wtc1f22.krn&f=kern` works!
Is that last one stable? I'm putting it in for now.

Corelli:
- @malcolmsailor [https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op1&file=op01n01a.krn&f=kern](https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op1&file=op01n01a.krn&f=kern) works for me. Which file/s did you notice issue/s with?

Chopin notes:
- @malcolmsailor both the git [https://raw.githubusercontent.com/craigsapp/chopin-mazurkas/master/kern/mazurka68-2.krn](https://raw.githubusercontent.com/craigsapp/chopin-mazurkas/master/kern/mazurka68-2.krn) and external [https://kern.humdrum.org/cgi-bin/ksdata?l=users/craig/classical/chopin/mazurka&file=mazurka06-1.krn&f=kern](https://kern.humdrum.org/cgi-bin/ksdata?l=users/craig/classical/chopin/mazurka&file=mazurka06-1.krn&f=kern) formats works for me. Which file/s did you notice issue/s with?

Copying @craigsapp in case you can provide any tips on current set up and / or future plans here. Thanks.

Also FYI, as well as some being blank, simply clicking through the kern website leads to some of this:
```
Access Unsuccessful:
location  = ccarh/class/2008/craig/bachchorale
format    = info
file      = chor024.krn
````

**Comment by malcolmsailor** [comment]
Why did you delete three of my comments? It means I'm not entirely sure what I have previously said or what I'm responding to. Did I say something about Chopin? I don't see anything about Chopin in my undeleted comments. Anyways, I can rerun the script and see again which filenames it gives.

**Comment by malcolmsailor** [comment]
Here's the full output of the script:
[download_errors.txt](https://github.com/MarkGotham/When-in-Rome/files/12620647/download_errors.txt)

I see that it's not in fact all Corelli files, just a large number of them. For example https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op3&file=op03n02b.krn&f=kern

I don't believe I said anything about Chopin humdrum files but I can't be sure since some of my comments have been deleted.

**Comment by malcolmsailor** [comment]
> * `https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/bach/keyboard/wtc&file=wtc1f22.krn&f=kern` is access unsuccessful
> * `https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/bach/keyboard/wtc&file=wtc1f22.krn&f=kern` works!

What is the difference? They appear to be the same.

**Comment by MarkGotham** [comment]
> > * `https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/bach/keyboard/wtc&file=wtc1f22.krn&f=kern` is access unsuccessful
> > * `https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/bach/keyboard/wtc&file=wtc1f22.krn&f=kern` works!
> 
> What is the difference? They appear to be the same.

Apologies. First should read `https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/bach/keyboard/wtc1&file=wtc1f22.krn&f=kern`

**Comment by MarkGotham** [comment]
(i.e. wtc1)

**Comment by MarkGotham** [comment]
Bach Chorales
- Ah yes, 150 missing from Sapp collection. Exception added to script

**Comment by MarkGotham** [comment]
Corelli:
- Op1 takes the format https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op1&file=op01n03a.krn&f=kern
- Op3 is different https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op3&file=op3n1-04.krn&f=kern

@craigsapp makes us work for it!

**Comment by MarkGotham** [comment]
Better still, the DCML have gone consistently with the op1 format.

**Comment by MarkGotham** [comment]
Ok g2g. I hope that's sorted the worst of it.

@malcolmsailor - I'd be grateful for an updated (hopefully much shorter!) error report if you'd be so kind.

**Comment by malcolmsailor** [comment]
I just fetched the latest version of the repo and reran the script.

[errors.txt](https://github.com/MarkGotham/When-in-Rome/files/12621301/errors.txt)

**Comment by MarkGotham** [comment]
Thanks @malcolmsailor.

All issues sorted except those now with dedicated issues.

Latest and last are these Corelli movements:

https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op4&file=op4n2-02.krn&f=kern
https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op4&file=op4n2-04.krn&f=kern
https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op4&file=op4n4-04.krn&f=kern
https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op4&file=op4n10-05.krn&f=kern
https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op4&file=op4n10-04.krn&f=kern
https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op4&file=op4n10-01.krn&f=kern
https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op4&file=op4n1-04.krn&f=kern
https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op4&file=op4n1-02.krn&f=kern
https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op4&file=op4n6-06.krn&f=kern
https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op4&file=op4n6-07.krn&f=kern
https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op4&file=op4n6-05.krn&f=kern
https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op4&file=op4n6-01.krn&f=kern
https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op4&file=op4n6-04.krn&f=kern
https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op4&file=op4n7-05.krn&f=kern
https://kern.humdrum.org/cgi-bin/ksdata?l=musedata/corelli/op4&file=op4n7-02.krn&f=kern

Summary:
- the URL _format_ is now correct
- these files are indeed not present on `kern.humdrum`
- they may result from movements combinations (e.g., DCML have 4; Craig has 3 with 2 joined). This is typical for short Baroque movements.

Proposal:
- only solution I see would be:
  - download a local (not doing for licence reasons) and 
  - split movements (doable, but a bit complex)
- do not implement that "solution" do that (do nothing) for now because ...
  - we also have working DCML remote score options in these case
- simply comment out krn sources _throughout_ for now (remove but easy to reinstate)
- Revisit if someone desperately wants this functionality or if the kern hosting pattern changes (both unlikely) .
- create a dedicated issue now copying all this
- close this issue
